.github/pull_request_template.md
.github/workflows/ci.yaml
.github/workflows/pr_validate.yaml
README.md
python/README.md

Replace all 'hms-dbmi-cellenics' references with 'biomage-org'
N/A
master

Replace hms-dbmi references with biomage-org

---

.flux.yaml

Fix a reference to old org

---

r/Dockerfile

Trying the symlink command just before starting the app

---

chart-infra/templates/pod-template.tpl
chart-infra/templates/scale-to-zero.yaml

I am adding this label to the pod in order to restrict the pods related to the worker environment that can run in fargate. Currently, there is no label set so the "scale down" job for the worker ends up running in fargate which is much more expensive than running in the node.
N/A
master

Added label:worker to pod template

---

.github/workflows/ci.yaml
chart-infra/templates/scale-to-zero.yaml

Scale staging default worker pods to 0
https://biomage.atlassian.net/browse/BIOMAGE-2190
N/A
N/A
N/A
master
N/A

[BIOMAGE-2190] - Scale staging default to 0

---

.github/workflows/ci.yaml
r/work.R

Add timestamp to image name in prep for Flux v2
Pushed and tagged properly:
N/A
N/A
UI - https://github.com/biomage-org/ui/pull/109
API - https://github.com/biomage-org/api/pull/54
Pipeline - https://github.com/biomage-org/pipeline/pull/65
Worker - https://github.com/biomage-org/worker/pull/50
master

Add timestamp to image name

---

python/src/worker/tasks/differential_expression.py
r/R/differential_expression.R
r/tests/testthat/test-differential_expression.R

https://biomage.atlassian.net/browse/BIOMAGE-2184
https://ui-grasp6-ui102-worker44.scp-staging.biomage.net/
https://github.com/biomage-org/ui/pull/102
master

[BIOMAGE-2184] Improve DifferentialExpression work response schema

---

.flux.yaml
.github/workflows/ci.yaml

Scope image update automation
https://biomage.atlassian.net/browse/BIOMAGE-2211
N/A
N/A
master

Scope image update automation

---

.flux.yaml

https://biomage.atlassian.net/browse/BIOMAGE-2285
N/A
N/A
master

Remove branch from flux.yaml

---

.github/workflows/ci.yaml

Increasing the worker memory in production, and decreasing it in staging.
https://biomage.atlassian.net/browse/BIOMAGE-2283
N/A
N/A
master

[BIOMAGE-2283] Increase memory in production

---

.flux.yaml

Add chart reconcile strategy
N/A
N/A
N/A
master

add chart reconcile strategy

---

r/Dockerfile
r/renv.lock
r/renv.lock.init
r/renv/.gitignore
r/renv/activate.R
r/setup/sysdeps_build_debian.txt
r/tests/testthat/test-trajectory_analysis.R

Update R to fix worker build, which fails due to the R package `nloptr`, which requires nlopt > 2.7, which is only available in ubuntu jammy, which is the ubuntu version used by Rocker starting from R-4.2.2.
This also makes R quiet (by adding the `-q` and `-s` flags to R calls in the dockerfile (fixing the call to conda clean).
Updates renv to the latest version.
Makes trajectory analysis tests a bit more stable by using better datasets and removing unnecessary checks.
Finally, updates the `renv.lock.init` to the state of the current `renv.lock`, to take build times back from 2.5h to 1.5h.
N/A
https://ui-german-worker61.scp-staging.biomage.net/
master
Have best practices and ongoing refactors being …

Update r 4.2.2

---

.github/workflows/ci.yaml

Increasing the memory for two experiments that were running out of it.
N/A
N/A
master

increased R worker memory to 44Gi

---

r/R/differential_expression.R

This PR transforms the adjusted p-values = 0 to the smallest representable number in R, to be able to plot these genes in the volcano plot, where we plot the log(adjusted p-values) on the y-axis. Currently, we are not plotting them because log(0) = Inf. 
Staging: https://ui-sara-worker63.scp-staging.biomage.net/
N/A
N/A
master

[BIOMAGE-2362] Transform zeros to very small numbers after differential expression

---

r/R/cluster.R
r/tests/testthat/test-cluster.R

Clustering breaks if the number of dimensions to be used (we use the default of 10) is higher than the number of available dimensions (calculated when running integration/PCA). This PR fixes that.
https://biomage.atlassian.net/browse/BIOMAGE-2399
N/A
https://github.com/biomage-org/pipeline/pull/126
master

[BIOMAGE-2399] - lower clustering dimensions for low dimensional datasets

---

r/work.R

print sessioninfo when starting worker.
N/A
N/A
master

add sessioninfo to worker

---

r/R/pseudobulk_differential_expression.R

Details here: https://this-is-biomage.slack.com/archives/C01CP46TJ0Z/p1677658448057719
https://biomage.atlassian.net/browse/BIOMAGE-2308
https://ui-ahriman-worker78.scp-staging.biomage.net/
master

[BIOMAGE-2308] Retrieving gene names from data in pseudobulk DE

---

chart-infra/templates/datadog-sidecar-permissions.yaml
chart-infra/templates/pod-template.tpl

Enable datadog
N/A
N/A
Pipeline - https://github.com/biomage-org/pipeline/pull/137
Worker - https://github.com/biomage-org/worker/pull/79
master

Enable datadog

---

python/Dockerfile
r/Dockerfile

N/A
https://ui-martinfosco-worker76.scp-staging.biomage.net/
master

Disable hot reload

---

python/src/tests/tasks/test_cluster_cells.py
python/src/worker/tasks/cell_annotation_sctype.py
python/src/worker/tasks/cluster_cells.py
r/R/cell_annotation_sctype.R
r/R/cluster.R

https://biomage.atlassian.net/browse/BIOMAGE-2430
https://ui-martinfosco-worker82.scp-staging.biomage.net/
master

[2430] Sctype clusters fix for old exps

---

.github/workflows/ci.yaml
.github/workflows/pr_validate.yaml

Fix PR formatting
N/A
N/A
N/A
master

Fix PR formatting

---

.github/workflows/ci.yaml

Reduce replica count in production to 1 for cost saving purposes

---

python/src/tests/tasks/test_batch_differential_expression.py
python/src/worker/tasks/batch_differential_expression.py

https://biomage.atlassian.net/browse/BIOMAGE-2454
https://ui-batchde-fix.scp-staging.biomage.net/
master

[BIOMAGE-2454] Batch differential expression within samples broken

---

README.md
python/README.md

Pre-merge pending changes

---

.github/workflows/pr_validate.yaml

Hms review changes

---

chart-infra/templates/scale-to-zero.yaml

replaced deprecated batch/v1beta
